### ISSUE TITLE
Can't add extra headers like it is implemented on java or kotlin

### ISSUE THREAD

**Issue by nazirjonmakhmadkulov** [T-Fowl/socket-io-coroutines#15]
Add possibility to add extraheaders to start connection like it is implemented java or kotlin

**Comment by T-Fowl** [comment]
Creating a `Socket` instance is outside the scope of these extensions, only connecting, emitting and listening to events are supported. It should still be possible to add extra headers by configuring a `IO.Options` parameter when creating a new `Socket`.

https://socketio.github.io/socket.io-client-java/initialization.html#extraHeaders

Closing as out of scope
